name: Build All Samples

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-all:
    name: Build and Test All Samples
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
      
      - name: Set up JDK 24
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '24'
      
      - name: Make build-all.sh executable
        run: chmod +x build-all.sh
      
      - name: Run build-all script
        run: ./build-all.sh
